services:
  database:
    image: pgvector/pgvector:pg16
    command: -c 'max_connections=500'
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./../tutor_service/pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_CREATE_DB_TUTOR_SERVICE=tutor_service
  app-tutor:
    build:
      context: ./../tutor_service # necessary because otherwise docker-compose overrides the context path when merging multiple docker-compose.yml files
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: tutor_service
    expose:
      - 1300
      - 1301
    ports:
      - "1300:1300"
      - "1301:1301"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/tutor_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  dapr-tutor:
    image: "daprio/daprd"
    command: [
      "./daprd",
      "--app-id", "tutor_service",
      "--app-port", "1301",
      "--dapr-http-port", "1300",
      "--resources-path", "./components"
    ]
    volumes:
      - "./../tutor_service/components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - app-tutor
      - redis
    network_mode: "service:app-tutor"
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
volumes:
  dbdata:
  testdata:
networks:
  default:
    name: dapr-network
    external: true
